import React from 'react';
import { ArrowLeft, FileText } from 'lucide-react';

const TermsConditions = () => {
  const goBack = () => {
    window.history.back();
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-white">
      {/* Header */}
      <div className="bg-white shadow-sm border-b">
        <div className="max-w-4xl mx-auto px-4 py-6">
          <button
            onClick={goBack}
            className="flex items-center gap-2 text-gray-600 hover:text-gray-800 transition-colors duration-200 mb-4"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </button>
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-gradient-to-r from-purple-500 to-pink-500 rounded-2xl flex items-center justify-center">
              <FileText className="w-6 h-6 text-white" />
            </div>
            <h1 className="text-3xl font-poppins font-bold text-gray-800">Terms & Conditions</h1>
          </div>
          <p className="text-gray-600 mt-2">Effective Date: 7/08/2025</p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-12">
        <div className="bg-white rounded-3xl shadow-lg p-8 md:p-12">
          <div className="space-y-6">
            <p className="text-gray-600 leading-relaxed">
              This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as
              applicable and the amended provisions pertaining to electronic records in various statutes as amended by the
              Information Technology Act, 2000. This electronic record is generated by a computer system and does not require
              any physical or digital signatures.
            </p>
            <p className="text-gray-600 leading-relaxed">
              This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology
              (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and
              Terms of Use for access or usage of domain name
              <a href="https://learn.nhancio.com" className="text-purple-600 hover:underline"> https://learn.nhancio.com</a>
              ("Website"), including the related mobile site and mobile application (hereinafter referred to as "Platform").
            </p>
            <p className="text-gray-600 leading-relaxed">
              The Platform is owned by NHANCIO TECHNOLOGIES PRIVATE LIMITED, a company incorporated under the Companies Act,
              1956 with its registered office at Devammabasthi, Jagadgirigutta, Balanagar Township, Rangareddy, Hyderabad -
              500037, Telangana, Hyderabad, India (hereinafter referred to as "Platform Owner", "we", "us", "our").
            </p>
            <p className="text-gray-600 leading-relaxed">
              Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of
              Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of
              reference. If you transact on the Platform, you shall be subject to the policies that are applicable to the
              Platform for such transaction. By mere use of the Platform, you shall be contracting with the Platform Owner and
              these terms and conditions including the policies constitute your binding obligations with the Platform Owner.
              These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable)
              (collectively, "Services"). Any terms and conditions proposed by you which are in addition to or which conflict
              with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These
              Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically
              review these Terms of Use to stay informed of updates.
            </p>
            <p className="text-gray-600 leading-relaxed">
              For the purpose of these Terms of Use, wherever the context so requires "you", "your" or "user" shall mean any
              natural or legal person who has agreed to become a user/buyer on the Platform.
            </p>
            <p className="text-gray-800 font-semibold">Accessing, browsing or otherwise using the Platform indicates your agreement to all the terms and conditions under these Terms of Use, so please read the Terms of Use carefully before proceeding.</p>

            <h2 className="text-xl font-poppins font-bold text-gray-800 mt-8">Use of Platform and Services</h2>
            <ul className="list-disc list-inside space-y-3 text-gray-600 leading-relaxed mt-2">
              <li>
                To access and use the Services, you agree to provide true, accurate and complete information to us during and
                after registration, and you shall be responsible for all acts done through the use of your registered account on
                the Platform.
              </li>
              <li>
                Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance,
                completeness or suitability of the information and materials offered on this website or through the Services, for
                any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and
                we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
              </li>
              <li>
                Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we
                shall not be liable to you in any manner. You are required to independently assess and ensure that the Services
                meet your requirements.
              </li>
              <li>
                The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any
                authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and
                is not limited to the design, layout, look and graphics.
              </li>
              <li>
                You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per
                these Terms of Use and/or applicable laws.
              </li>
              <li>
                You agree to pay us the charges associated with availing the Services.
              </li>
              <li>
                You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these
                Terms, or Indian or local laws that might apply to you.
              </li>
              <li>
                You agree and acknowledge that the Website and the Services may contain links to other third party websites. On
                accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such
                third party websites. These links are provided for your convenience to provide further information.
              </li>
              <li>
                You understand that upon initiating a transaction for availing the Services you are entering into a legally
                binding and enforceable contract with the Platform Owner for the Services.
              </li>
              <li>
                You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies (as applicable) and
                their respective officers, directors, agents, and employees, from any claim or demand, or actions including
                reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of your breach of
                these Terms of Use, Privacy Policy and other Policies, or your violation of any law, rules or regulations or the
                rights (including infringement of intellectual property rights) of a third party.
              </li>
              <li>
                Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to
                perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
              </li>
            </ul>

            <h2 className="text-xl font-poppins font-bold text-gray-800 mt-8">Governing Law and Jurisdiction</h2>
            <p className="text-gray-600 leading-relaxed">
              These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in
              accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to
              the exclusive jurisdiction of the courts in Hyderabad and Telangana.
            </p>

            <h2 className="text-xl font-poppins font-bold text-gray-800 mt-8">Contact</h2>
            <p className="text-gray-600 leading-relaxed">
              All concerns or communications relating to these Terms must be communicated to us using the contact information
              provided on this website.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsConditions; 